module.exports = {
  config: {
    name: "emoji_react",
    version: "1.0",
    author: "chris st",
    countDown: 5,
    role: 0,
    shortDescription: "Réponses aux emojis variés",
    longDescription: "Réponses provocantes et humoristiques adaptées aux emojis",
    category: "reply",
  },

  onStart: async function () {},

  onChat: async function ({ event, message }) {
    const emoji = event.body.trim();

    const responses = {
      "😂": [
        "Tu rigoles fort mais ta vie reste une blague.",
        "Mdrrr calme-toi clown professionnel.",
        "Tu ris comme si quelqu’un t’avait enfin répondu.",
        "Même ton rire demande de l’aide.",
        "T’es mort de rire mais toujours vivant malheureusement.",
      ],

      "💀": [
        "Le crâne te représente parfaitement.",
        "Même les morts veulent pas de toi.",
        "Ton niveau d’intelligence repose en paix.",
        "💀 = ton cerveau après une réflexion.",
        "T’es tellement éclaté que même ce emoji a peur.",
      ],

      "😹": [
        "Le chat rigole plus fort que toi.",
        "T’es devenu le comique du village ?",
        "Même les chats te prennent pas au sérieux.",
        "Tu rigoles trop pour quelqu’un d’aussi perdu.",
        "Le chat pleure de rire… ou de honte.",
      ],

      "😴": [
        "Tu dors encore ? Comme ton avenir.",
        "Réveille-toi, la défaite continue.",
        "T’es fatigué d’être inutile ?",
        "Même endormi tu sers à rien.",
        "Ton cerveau est en mode économie d’énergie.",
      ],

      "🐒": [
        "Ton cousin vient d’envoyer un emoji.",
        "Le singe est plus discipliné que toi.",
        "On a trouvé ton animal spirituel.",
        "Même ce singe réfléchit mieux.",
        "Tu lui ressembles un peu trop.",
      ],

      "🧠": [
        "Oh un cerveau ? Rends-le à son propriétaire.",
        "T’envoies ça comme si t’en avais un.",
        "Erreur système : cerveau introuvable.",
        "Le cerveau travaille mais pas chez toi.",
        "Emoji rare dans tes messages.",
      ],

      "😎": [
        "Tu fais le boss mais t’es en mode brouillon.",
        "Les lunettes cachent pas la honte.",
        "T’es frais seulement dans tes rêves.",
        "Même avec le style t’es perdu.",
        "Le swag sans cerveau ça reste dangereux.",
      ],

      "🥶": [
        "T’es glacé comme tes conversations.",
        "Le froid a gelé ton dernier neurone.",
        "Tu trembles ou c’est la honte ?",
        "Même la glace a plus de chaleur.",
        "Ton charisme est en hypothermie.",
      ],

      "😡": [
        "Tu t’énerves pour cacher ta faiblesse ?",
        "Respire avant de casser ton clavier.",
        "La colère va pas augmenter ton QI.",
        "T’es fâché mais toujours ridicule.",
        "Même énervé t’es pas intimidant.",
      ],

      "🤢": [
        "Exactement la tête des gens quand tu parles.",
        "Ton humour donne cet effet-là.",
        "Même l’emoji est dégoûté.",
        "T’as vu ton reflet encore ?",
        "Ça résume parfaitement ta présence.",
      ],

      "🐍": [
        "Le serpent reconnaît un des siens.",
        "T’es discret mais toxique.",
        "Même les serpents ont peur de toi.",
        "Tu glisses partout sauf vers le succès.",
        "Le venin te va bien.",
      ],

      "🐀": [
        "Le rat du quartier est arrivé.",
        "Toujours caché quand ça chauffe.",
        "Même les égouts t’ont refusé.",
        "Petit rat mais grande bouche.",
        "Tu cours vite dès qu’il y a problème.",
      ],

      "👽": [
        "Même les aliens comprennent pas ton comportement.",
        "T’as vraiment l’air venu d’une autre planète.",
        "OVNI détecté dans le chat.",
        "Retourne sur Mars stp.",
        "Même les extraterrestres ont plus de logique.",
      ],

      "❤️": [
        "Tu donnes ton cœur trop facilement.",
        "Même l’amour peut pas sauver ton cas.",
        "Le cœur est rouge comme tes regrets.",
        "T’es amoureux ou juste faible ?",
        "L’amour rend aveugle… ça explique beaucoup.",
      ],

      "😏": [
        "Pourquoi tu souris comme un méchant de série ?",
        "Ton regard suspect inquiète tout le monde.",
        "T’as préparé une bêtise encore ?",
        "Le sourire bizarre du quartier.",
        "Même ton emoji paraît louche.",
      ],

      "🙄": [
        "Tes yeux tournent mais ton cerveau reste bloqué.",
        "Arrête de lever les yeux, trouve une idée déjà.",
        "Même ton regard abandonne.",
        "Tu juges beaucoup pour quelqu’un comme toi.",
        "Tes yeux cherchent l’intelligence ? Bonne chance.",
      ],

      "😢": [
        "Pleure pas, ça changera rien.",
        "Tes larmes veulent quitter ce niveau de vie.",
        "Même triste t’es dramatique.",
        "Le mode victime encore ?",
        "Tu pleures plus que tu réfléchis.",
      ],

      "🔥": [
        "Oh, du feu ! Fais gaffe, t’es déjà cramé dans la vie.",
        "Tu veux brûler quoi ? Tes rêves ? C’est déjà fait.",
        "T’es en feu ? Plutôt en train de fumer ton échec.",
        "Arrête de jouer avec le feu, t’es déjà en cendres.",
        "Flamme ou pas, t’éclaires toujours rien.",
      ],

      "🤡🔥": [
        "Le clown est maintenant en feu, magnifique catastrophe.",
        "Tu combines honte et destruction.",
        "Le cirque brûle à cause de toi.",
        "Même le feu veut te supprimer.",
        "Catastrophe naturelle détectée.",
      ],
      "😂": [
  "Tu rigoles fort pour quelqu’un qui comprend rien.",
  "Mdrrr même ton rire a l’air perdu.",
  "Tu ris comme si ta vie était stable.",
  "Le seul spectacle ici, c’est toi.",
  "Continue de rire, c’est tout ce qu’il te reste.",
  "Même les clowns trouvent ça excessif.",
  "Ton rire cache une grande détresse.",
  "T’as lancé un fou rire ou un bug système ?",
  "Tu rigoles mais personne a raconté de blague.",
  "Le rire est gratuit, heureusement pour toi.",
],

"💀": [
  "Le crâne représente ton cerveau actuellement.",
  "Même les morts veulent pas de toi.",
  "Ton intelligence repose en paix.",
  "💀 = ton niveau après une réflexion.",
  "T’es tellement éclaté que même ce emoji te juge.",
  "On dirait ton avenir après tes choix.",
  "Même un squelette a plus de présence.",
  "Le mode fantôme te correspond bien.",
  "T’es fini comme ce crâne.",
  "Ton dernier neurone vient de quitter le serveur.",
],

"🤡": [
  "Merci d’avoir envoyé ton portrait.",
  "Le cirque réclame son employé.",
  "Même les clowns ont honte pour toi.",
  "T’es drôle malgré toi.",
  "Le maquillage est invisible mais l’énergie est là.",
  "Tu fais rire sans effort, triste talent.",
  "On a trouvé la star du chapiteau.",
  "T’es un spectacle ambulant.",
  "Même le clown du McDo est plus crédible.",
  "Ton existence entière est un sketch.",
],

"😴": [
  "Tu dors encore ? Comme ton avenir.",
  "Réveille-toi, la défaite continue.",
  "Même endormi tu sers à rien.",
  "Ton cerveau est en veille depuis longtemps.",
  "Tu récupères de quelle fatigue exactement ?",
  "Le sommeil fuit ta réalité.",
  "Tu pionces plus que tu réfléchis.",
  "Même dans tes rêves t’échoues.",
  "Ton activité principale : dormir.",
  "T’es fatigué d’être inutile ?",
],

"😡": [
  "Tu t’énerves mais ça fait pas peur.",
  "Respire avant de casser ton écran.",
  "La colère augmente pas ton QI.",
  "Même fâché t’as l’air perdu.",
  "Tu fais le méchant mais t’es sensible.",
  "Ton énervement amuse plus qu’autre chose.",
  "Le démon intérieur a besoin d’un repos.",
  "T’es rouge de rage ou de honte ?",
  "Même ton emoji veut se calmer.",
  "Tu cries fort pour cacher ton manque d’arguments.",
],

"🥶": [
  "Le froid a gelé ton dernier neurone.",
  "T’es glacé comme tes conversations.",
  "Même la banquise a plus de chaleur.",
  "Ton charisme est en hypothermie.",
  "Tu trembles ou c’est la honte ?",
  "Le froid te va bien, t’as déjà le cœur vide.",
  "Même l’hiver est moins gênant.",
  "T’es plus froid qu’un vu sans réponse.",
  "Ton énergie est congelée.",
  "Même le climat veut t’éviter.",
],

"🐍": [
  "Le serpent reconnaît un des siens.",
  "T’es discret mais toxique.",
  "Même les serpents ont peur de toi.",
  "Tu rampes partout sauf vers le succès.",
  "Le venin te représente bien.",
  "On sent la trahison à des kilomètres.",
  "T’as une tête à vendre tes amis.",
  "Le reptile officiel du groupe.",
  "Même un cobra est plus honnête.",
  "Tu glisses dans les problèmes naturellement.",
],

"🐀": [
  "Le rat du quartier est connecté.",
  "Toujours caché quand ça chauffe.",
  "Même les égouts t’ont refusé.",
  "Petit rat mais grande bouche.",
  "Tu cours vite dès qu’il y a danger.",
  "Le roi des disparitions.",
  "Même Jerry est plus courageux.",
  "Tu survis grâce à la fuite.",
  "Rat professionnel certifié.",
  "Ton courage est en mode avion.",
],

"🧠": [
  "Oh un cerveau ? Rends-le à son propriétaire.",
  "T’envoies ça comme si t’en avais un.",
  "Erreur système : intelligence introuvable.",
  "Emoji rare dans tes messages.",
  "Le cerveau travaille mais pas chez toi.",
  "Même Google trouve pas tes idées.",
  "T’as envoyé ça par accident ?",
  "Le QI essaye de se connecter.",
  "Ton cerveau est en maintenance permanente.",
  "On dirait une pièce de collection chez toi.",
],

"❤️": [
  "Tu donnes ton cœur trop facilement.",
  "Même l’amour peut pas sauver ton cas.",
  "Le cœur est rouge comme tes regrets.",
  "T’es amoureux ou juste naïf ?",
  "L’amour t’a rendu aveugle apparemment.",
  "Même Cupidon t’a bloqué.",
  "Ton cœur mérite un meilleur propriétaire.",
  "Tu tombes amoureux plus vite qu’une connexion lente.",
  "Le romantisme te rend faible.",
  "Ton cœur travaille plus que ton cerveau.",
],

"🙄": [
  "Tes yeux tournent mais ton cerveau reste bloqué.",
  "Arrête de lever les yeux et trouve une idée.",
  "Même ton regard abandonne.",
  "Tu juges beaucoup pour quelqu’un comme toi.",
  "Tes yeux cherchent l’intelligence ? Bonne chance.",
  "Le mépris te va pas du tout.",
  "T’as l’air fatigué des conséquences de tes choix.",
  "Même tes yeux veulent quitter la conversation.",
  "Ton regard est aussi vide que tes arguments.",
  "Tu souffles beaucoup pour quelqu’un d’inutile.",
],

"😏": [
  "Pourquoi tu souris comme un méchant raté ?",
  "Ton regard suspect inquiète tout le monde.",
  "T’as préparé une bêtise encore ?",
  "Le sourire bizarre du quartier.",
  "Même ton emoji paraît louche.",
  "Tu fais le mystérieux mais t’es prévisible.",
  "Ton sourire cache une mauvaise idée.",
  "Même les villains ont plus de style.",
  "On dirait un PNJ suspect.",
  "T’as une tête à faire des plans inutiles.",
],

"👽": [
  "Même les aliens te trouvent bizarre.",
  "Retourne sur ta planète stp.",
  "OVNI détecté dans le chat.",
  "T’as vraiment une énergie extraterrestre.",
  "Même la NASA peut pas t’expliquer.",
  "T’es différent… mais pas dans le bon sens.",
  "Les extraterrestres refus
    };

"😐": [
  "Même ton visage a abandonné.",
  "T’as l’air vide comme tes arguments.",
  "Cette expression résume ton énergie.",
  "Même un mur a plus d’émotions.",
  "Tu regardes comme un PNJ buggué.",
  "Ton humeur est en économie d’énergie.",
  "Le néant en une expression.",
  "T’as freeze ou quoi ?",
  "Même les robots sont plus expressifs.",
  "Ton visage charge encore les émotions.",
],

"😑": [
  "Ton regard juge mais ton niveau suit pas.",
  "Même toi t’es fatigué de toi-même.",
  "Le dégoût dans tes yeux est mérité.",
  "Tu fixes cmme si t’avais compris quelque chose.",
  "Ton expression est aussi sèche que tes discussions.",
  "On dirait un prof déçu par un élève nul.",
  "Même tes yeux veulent quitter la conversation.",
  "T’as l’air blasé depuis la naissance.",
  "Ton âme est en mode hors ligne.",
  "Même ton emoji semble déprimé.",
],

"🤓": [
  "Le génie du village est arrivé.",
  "Tu corriges les gens mais pas ta vie.",
  "Même tes lunettes ont honte.",
  "T’as appris un mot compliqué et maintenant tu forces.",
  "Le Wikipédia humain inutile.",
  "Tu parles comme un prof sans salaire.",
  "Même Google veut moins d’explications.",
  "T’es intelligent uniquement dans ta tête.",
  "Le mode premier de classe est insupportable.",
  "Tu respires les devoirs maison.",
],

"😬": [
  "Ton sourire fait peur.",
  "Même ton emoji est gêné d’exister.",
  "On dirait que t’as vu tes notes.",
  "Le malaise est devenu une expression.",
  "Tu souris comme quelqu’un pris en faute.",
  "Même tes dents veulent fuir.",
  "T’as l’air stressé H24.",
  "Le sourire de la honte.",
  "On sent la panique derrière ce visage.",
  "Même ton emoji transpire la gêne.",
],

"🤨": [
  "Tu regardes bizarrement mais t’as aucune preuve.",
  "Même Sherlock te trouverait suspect.",
  "Ton doute est plus grand que ton intelligence.",
  "T’as levé un sourcil comme si t’étais important.",
  "Le regard du mec qui comprend à moitié.",
  "Même ton emoji juge tes choix.",
  "Tu cherches une logique ? Pas ici.",
  "On dirait un détective raté.",
  "Ton regard veut une explication impossible.",
  "Même tes sourcils sont confus.",
],

"😜": [
  "Tu tires la langue comme un enfant de 5 ans.",
  "Même ton humour est immature.",
  "T’as cru que t’étais drôle ?",
  "Le clown essaie encore.",
  "Ton énergie fatigue tout le monde.",
  "Même les gamins sont plus sérieux.",
  "Tu fais le fou pour cacher le vide.",
  "On dirait un bug d’hyperactivité.",
  "Ton emoji a besoin de repos.",
  "T’es le chaos incarné.",
],

"😇": [
  "Tu joues l’innocent maintenant ?",
  "Même les anges te regardent bizarrement.",
  "Le halo ne cache pas les dossiers.",
  "T’as l’air sage mais personne y croit.",
  "L’innocence a quitté le chat.",
  "Même ton emoji ment.",
  "Tu fais le saint après les dégâts.",
  "Le faux calme du démon discret.",
  "Même le paradis hésite.",
  "Ton comportement et cet emoji ne vont pas ensemble.",
],

"👻": [
  "Même les fantômes ont plus de présence.",
  "T’apparais seulement quand ça t’arrange.",
  "Le mode disparition est activé.",
  "On dirait ton activité dans les discussions.",
  "Même Casper est plus courageux.",
  "T’es invisible quand y’a des problèmes.",
  "Fantôme professionnel certifié.",
  "Tu réponds une fois tous les 6 mois.",
  "Même les morts sont plus actifs.",
  "Le revenant du groupe est connecté.",
],

"💩": [
  "Merci d’avoir envoyé ton portrait HD.",
  "Même les toilettes refusent ça.",
  "Ton niveau résumé en un emoji.",
  "L’odeur traverse l’écran.",
  "Même cet emoji a plus de valeur.",
  "On a trouvé ton énergie spirituelle.",
  "Le caca parle enfin.",
  "T’es une catastrophe biologique.",
  "Même les mouches prennent leurs distances.",
  "Ton existence est une pollution visuelle.",
],

"👹": [
  "Tu fais le démon mais t’as peur du noir.",
  "Même les monstres te trouvent bizarre.",
  "Le boss final du ridicule.",
  "T’as activé le mode rage inutile.",
  "Même l’enfer hésite à te prendre.",
  "Tu veux faire peur à qui exactement ?",
  "Ton énergie est démoniaque mais ratée.",
  "Le monstre du quartier est réveillé.",
  "Même ton emoji est agressif gratuitement.",
  "Tu ressembles à un villain secondaire.",
],

"👺": [
  "Tu caches quoi derrière ce masque ?",
  "Même les démons japonais sont plus polis.",
  "Ton regard est plus bizarre que menaçant.",
  "On dirait un boss raté de jeu vidéo.",
  "Le masque cache pas le manque de niveau.",
  "Même les yokai te jugent.",
  "T’as une énergie de méchant low budget.",
  "Le démon Wish du groupe.",
  "Même Naruto t’aurait ignoré.",
  "Ton aura fait bugger les gens.",
],

"😈": [
  "Tu fais le démon mais t’es fragile.",
  "Même le mal te trouve gênant.",
  "Le sourire du problème ambulant.",
  "T’as l’air fier d’être pénible.",
  "Même les villains ont plus de classe.",
  "Le chaos suit chacun de tes messages.",
  "Tu provoques puis tu disparais.",
  "Le mini démon du groupe.",
  "Ton sourire cache une mauvaise idée.",
  "Même Satan demande des explications.",
],

"🤖": [
  "Même les robots ont plus d’émotions.",
  "Ton cerveau fonctionne en version bêta.",
  "Erreur 404 : intelligence introuvable.",
  "Tu réponds comme une IA cassée.",
  "Le mode automatique est activé.",
  "Même ChatGPT te comprend pas.",
  "Ton système a besoin d’une mise à jour.",
  "Robot low-cost détecté.",
  "T’as été programmé par un clown ?",
  "Connexion au cerveau impossible.",
],

"🐸": [
  "La grenouille du quartier est là.",
  "Même Pepe te juge.",
  "Tu sautes partout sauf vers le succès.",
  "Le marécage t’attend champion.",
  "Même une grenouille a plus de charisme.",
  "T’as une énergie de meme raté.",
  "Coasse moins et réfléchis plus.",
  "Même les moustiques te fuient.",
  "Le prince est jamais arrivé.",
  "T’es coincé en mode amphibien.",
],

"🐵": [
  "Ton cousin vient de rejoindre le chat.",
  "Même le singe agit mieux que toi.",
  "T’as envoyé une photo de famille ?",
  "Le zoo réclame son influenceur.",
  "Même Tarzan est plus civilisé.",
  "Tu fais trop le sauvage.",
  "Le mode jungle est activé.",
  "Même les bananes ont peur.",
  "Tu grimpes partout sauf dans la vie.",
  "Le primate officiel du groupe.",
],

"🥱": [
  "Tu bâilles comme si ta vie était passionnante.",
  "Même ton ennui est fatiguant.",
  "T’es lassé de rien faire ?",
  "Ton énergie dort debout.",
  "Même les siestes t’évitent.",
  "Tu t’ennuies ou ton cerveau s’éteint ?",
  "Le manque d’intérêt te définit bien.",
  "Tu donnes sommeil à toute la discussion.",
  "Même ton emoji veut aller dormir.",
  "T’as l’air épuisé par ta propre existence.",
],

"🤤": [
  "Calme-toi avant de salir le sol.",
  "Même ton emoji est gênant.",
  "Tu baves sur quoi exactement ?",
  "Le mode affamé du cerveau est activé.",
  "Même les chiens ont plus de dignité.",
  "T’as vu de la nourriture ou juste un délire ?",
  "Ton niveau de concentration est liquide.",
  "Tu fais peur avec cette tête.",
  "Même ton clavier est en danger.",
  "La dignité vient de quitter le chat.",
],

"😵": [
  "Ton cerveau vient de quitter la partie.",
  "Même toi t’as plus compris ce qui se passe.",
  "Le bug mental est confirmé.",
  "Tu tournes plus que les ventilateurs.",
  "Même ton âme est confuse.",
  "Erreur critique détectée.",
  "Ton système vient de crash.",
  "Même les étoiles autour de ta tête sont perdues.",
  "T’as regardé tes notes ou quoi ?",
  "Le KO technique est validé.",
],

"🥴": [
  "T’as l’air perdu dans une autre dimension.",
  "Même ton emoji sait plus où il est.",
  "Tu marches droit au moins ?",
  "Le chaos a pris possession de ton visage.",
  "Même ta logique titube.",
  "T’as une connexion instable avec la réalité.",
  "Ton cerveau fait des zigzags.",
  "Même les bugs sont plus stables.",
  "On dirait un personnage après une mauvaise décision.",
  "Ton équilibre mental est en vacances.",
],

"😤": [
  "Tu souffles fort pour quelqu’un d’aussi faible.",
  "Même ta colère manque de motivation.",
  "Calme-toi avant de tomber en panne.",
  "Tu fais le taureau mais t’es un mouton.",
  "Le moteur chauffe pour rien.",
  "Même ton ego transpire.",
  "Tu t’énerves en HD maintenant ?",
  "Le mode frustration est activé.",
  "Même l’air que tu souffles est fatigué.",
  "Ton énervement est en carton.",
],

"🤯": [
  "Ton cerveau vient d’exploser après une seule pensée.",
  "Même les maths te mettent KO.",
  "Le peu de neurones restants abandonne.",
  "T’as découvert quelque chose d’incroyable ? La réflexion ?",
  "Même ton esprit est choqué par toi.",
  "Explosion mentale détectée.",
  "Ton cerveau supporte pas trop d’informations.",
  "Même Google bug moins que toi.",
  "Le savoir t’a frappé trop fort.",
  "Ton système vient de surchauffer.",
],

"😶": [
  "Même toi tu sais plus quoi dire.",
  "Le silence est la meilleure chose venant de toi.",
  "Ton cerveau charge encore la réponse.",
  "On dirait un PNJ sans dialogue.",
  "Même ton emoji est vide.",
  "T’as perdu les mots ou les idées ?",
  "Le néant total dans le regard.",
  "Même les murs parlent plus.",
  "Tu fixes l’écran sans comprendre.",
  "Le mode muet permanent.",
],

"🫠": [
  "Tu fonds sous la pression comme une glace au soleil.",
  "Même ton mental devient liquide.",
  "T’as abandonné tellement vite.",
  "Ton cerveau a littéralement fondu.",
  "Le malaise t’a transformé.",
  "Même ton emoji supporte plus la situation.",
  "Tu dégoulines de honte.",
  "Ton état mental est en fusion.",
  "Même la chaleur te respecte pas.",
  "Tu t’écroules émotionnellement en direct.",
],

"😬": [
  "Ton sourire ressemble à une erreur système.",
  "Même les dents sont stressées.",
  "Tu souris comme quelqu’un pris au piège.",
  "Le malaise est visible à 100%.",
  "Même ton emoji regrette.",
  "T’as l’air d’avoir raté quelque chose.",
  "Le sourire forcé du siècle.",
  "Même ton visage panique.",
  "On sent la honte derrière l’écran.",
  "Ton expression demande de l’aide.",
],

"🤧": [
  "Même ton nez abandonne.",
  "T’as attrapé le virus de la honte ?",
  "La maladie te reconnaît comme chef.",
  "Même ton rhume est dramatique.",
  "Tu éternues plus que tu réfléchis.",
  "Ton système immunitaire a quitté le groupe.",
  "Même les microbes sont gênés.",
  "Prends un mouchoir et du courage.",
  "T’as l’air détruit par un simple courant d’air.",
  "Même ton emoji est fatigué.",
],

"🥳": [
  "Tu fêtes quoi ? Ta dernière défaite ?",
  "Même la fête veut te bannir.",
  "Ton énergie est trop chaotique.",
  "Tu fais le fou pour rien.",
  "Même les confettis tombent de honte.",
  "Le clown festif est réveillé.",
  "T’as transformé le chat en anniversaire gênant.",
  "Même la musique veut s’arrêter.",
  "Tu danses comme un bug.",
  "Le mode fiesta sans raison.",
],

"😪": [
  "Même ton sommeil a l’air triste.",
  "Tu dors ou tu déprimes ?",
  "Ton énergie est en PLS.",
  "Même tes rêves sont fatigués.",
  "Le mode zombie est activé.",
  "Tu bâilles plus que tu vis.",
  "Ton cerveau veut une pause définitive.",
  "Même les coussins te jugent.",
  "T’as l’air détruit mentalement.",
  "Le sommeil est devenu ta personnalité.",
],

"🤠": [
  "Le cowboy du quartier est arrivé.",
  "Même les chevaux te fuient.",
  "Tu joues le shérif sans village.",
  "Le Far West mérite des excuses.",
  "Même ton chapeau est gêné.",
  "Cowboy low-cost détecté.",
  "Tu dégaines plus vite que tu réfléchis.",
  "Même les cactus te jugent.",
  "T’as une énergie de PNJ western.",
  "Le cowboy du dimanche.",
],

"😺": [
  "Le chat est plus intelligent que toi.",
  "Même les chats te regardent bizarrement.",
  "Tu miaules au lieu de réfléchir.",
  "Le félin du chaos est connecté.",
  "Même Garfield est plus productif.",
  "Tu cherches de l’attention comme un chat.",
  "Le mode animal domestique est activé.",
  "Même les croquettes te refusent.",
  "T’as une énergie de chat perdu.",
  "Le miaou de la honte.",
],

"🙃": [
  "Ton cerveau fonctionne à l’envers.",
  "Même ton emoji est perdu.",
  "Tu vois la vie retournée ou quoi ?",
  "Le chaos mental continue.",
  "Même tes idées marchent à l’envers.",
  "T’as inversé logique et bêtise.",
  "Ton humour est aussi stable que cet emoji.",
  "Même l’écran est confus.",
  "Tu retournes tout sauf ta situation.",
  "Le mode bug graphique est activé.",
],

"😹": [
  "Le chat rigole plus fort que toi.",
  "Même les chats trouvent ta vie drôle.",
  "Tu ris comme un dessin animé cassé.",
  "Le félin se moque de toi en direct.",
  "Même Tom aurait honte.",
  "Ton humour est en roue libre.",
  "Tu miaules de rire maintenant ?",
  "Même les animaux te trollent.",
  "Le chat est hilarant, toi moins.",
  "Ton fou rire est incontrôlable.",
],

"😻": [
  "Tu tombes amoureux toutes les 3 secondes.",
  "Même les chats sont plus discrets.",
  "Ton cœur bug encore.",
  "Le mode simp est activé.",
  "Même Cupidon te trouve gênant.",
  "Tu regardes les gens comme un PNJ amoureux.",
  "Ton emoji respire la faiblesse émotionnelle.",
  "Même le chat est plus stable sentimentalement.",
  "Tu crush trop facilement.",
  "L’amour t’a retiré le cerveau.",
],

"😼": [
  "Tu fais le malin mais ça prend pas.",
  "Même le chat a plus de confiance que toi.",
  "Ton sourire cache une bêtise.",
  "Le félin suspect du quartier.",
  "Tu te crois supérieur pour rien.",
  "Même les chats jugent moins.",
  "Ton arrogance est en 4K.",
  "Le mode sournois est activé.",
  "Même ton emoji a l’air toxique.",
  "Tu fais trop le boss.",
],

"🙀": [
  "Même le chat a peur de ta logique.",
  "Tu paniques vite pour rien.",
  "Le choc émotionnel est réel.",
  "Même ton emoji veut s’enfuir.",
  "T’as vu ton avenir ou quoi ?",
  "La peur a pris le contrôle.",
  "Même les chats crient moins fort.",
  "Ton âme vient de quitter le serveur.",
  "Tu sursautes comme un PNJ.",
  "Le stress t’a détruit.",
],

"😽": [
  "Tu distribues des bisous comme des pubs.",
  "Même le chat est plus romantique.",
  "Le mode affection gênante.",
  "T’es trop doux pour survivre ici.",
  "Même ton emoji rougit pour toi.",
  "Tu veux attendrir qui exactement ?",
  "Le romantisme est hors contrôle.",
  "Même les chats flirtent mieux.",
  "Ton cœur prend trop de place.",
  "Tu fais le lover du quartier.",
],

"🫡": [
  "Tu salues comme un soldat sans mission.",
  "Même l’armée te refuserait.",
  "Le respect ne te va pas.",
  "Tu fais trop le discipliné.",
  "Même ton emoji est sérieux pour rien.",
  "Capitaine inutile détecté.",
  "Tu donnes des ordres à personne.",
  "Le général du vide.",
  "Même les recrues sont plus crédibles.",
  "Ton autorité est imaginaire.",
],

"🤫": [
  "Tu caches un secret ou juste de la bêtise ?",
  "Même ton silence est suspect.",
  "Le mode espion est activé.",
  "Tu fais le mystérieux pour rien.",
  "Même les murs parlent plus que toi.",
  "Ton doigt sur la bouche change rien.",
  "Tu connais des trucs inutiles sûrement.",
  "Le silence du clown.",
  "Même ton emoji complote.",
  "Tu veux du calme mais tu crées le chaos.",
],

"🫢": [
  "Même toi t’es choqué par tes messages.",
  "Tu caches ta bouche mais pas la honte.",
  "Le malaise est monté trop vite.",
  "Même ton emoji regrette.",
  "Tu viens de dire une dinguerie ?",
  "Ton cerveau a parlé sans permission.",
  "Même les spectateurs sont gênés.",
  "La surprise a détruit ton système.",
  "Tu paniques après avoir parlé.",
  "Même ta bouche veut disparaître.",
],

"😳": [
  "Tu rougis plus vite qu’une connexion lente.",
  "Même ton emoji est embarrassé.",
  "Le stress social te détruit.",
  "Tu fais le timide maintenant ?",
  "Même ton visage chauffe.",
  "La honte t’a frappé en pleine tête.",
  "Tu bug quand quelqu’un te regarde.",
  "Même ton cœur panique.",
  "Ton émotion est visible à 100 km.",
  "Le mode gêne extrême est activé.",
],

"🥹": [
  "Tu vas pleurer pour si peu ?",
  "Même ton emoji demande un câlin.",
  "Le mode fragile est activé.",
  "Tu regardes comme un personnage triste.",
  "Même la compassion te fuit.",
  "Ton regard veut manipuler les gens.",
  "T’as l’air trop sensible pour internet.",
  "Même les émotions te dominent.",
  "Tu cherches de la pitié gratuitement.",
  "Le regard du chiot abandonné.",
],

"😋": [
  "Tu salives encore ?",
  "Même la nourriture te juge.",
  "Ton ventre contrôle ta vie.",
  "Le gourmand officiel du groupe.",
  "Même ton emoji a faim H24.",
  "Tu penses plus à manger qu’à réfléchir.",
  "Ton cerveau est remplacé par un menu.",
  "Même les snacks ont peur.",
  "Tu regardes la bouffe avec amour.",
  "Le mode affamé permanent.",
],

"😛": [
  "Tu tires la langue comme un enfant.",
  "Même ton humour est immature.",
  "Le clown du groupe est réveillé.",
  "Tu fais le fou sans raison.",
  "Même ton emoji fatigue.",
  "Tu cherches l’attention encore.",
  "Ton énergie est incontrôlable.",
  "Même les gamins sont plus sérieux.",
  "Tu respires le chaos.",
  "Le mode débile est activé.",
],

"🤑": [
  "Tu fais le riche avec 2 pièces.",
  "Même ton portefeuille pleure.",
  "Le businessman du quartier sans business.",
  "Tu comptes l’argent des autres.",
  "Même ton emoji ment.",
  "T’as l’air riche uniquement en rêves.",
  "Le capitalisme t’a détruit.",
  "Tu veux l’argent sans travailler.",
  "Même les banques te bloquent.",
  "Ton compte est plus vide que ton regard.",
],

"😰": [
  "Tu stresses comme si le monde allait finir.",
  "Même ton emoji transpire la peur.",
  "Le mode panique est activé.",
  "Tu réfléchis trop pour rien.",
  "Même ton cerveau chauffe.",
  "Le stress te contrôle totalement.",
  "Tu trembles devant des problèmes faciles.",
  "Même les examens font moins peur.",
  "Ton calme a quitté le serveur.",
  "Tu survis grâce à l’angoisse.",
],

"🤪": [
  "Ton cerveau fait des saltos.",
  "Même la folie te trouve bizarre.",
  "Tu respires le chaos pur.",
  "Le clown possédé du groupe.",
  "Même ton emoji est incontrôlable.",
  "Tu fais peur mentalement.",
  "Le mode délire est activé.",
  "Même les fous te regardent mal.",
  "Ton énergie est interdite.",
  "Tu bug émotionnellement.",
],

"💤": [
  "Même ton emoji dort mieux que toi.",
  "Le sommeil est devenu ton métier.",
  "Tu dors pour éviter la réalité ?",
  "Même les lits sont fatigués de toi.",
  "Ton cerveau est en veille permanente.",
  "Tu pionces plus que tu réfléchis.",
  "Le mode hibernation est activé.",
  "Même ton réveil a abandonné.",
  "Tu fais des siestes émotionnelles.",
  "Le roi des dormeurs inutiles.",
],

"💯": [
  "Tu mets 100 mais t’es à peine à 10.",
  "Même ton niveau refuse ce emoji.",
  "Tu forces trop la confiance.",
  "Le faux perfectionniste du groupe.",
  "Même les notes scolaires te contredisent.",
  "Tu te notes toi-même maintenant ?",
  "Le 100% imaginaire.",
  "Ton ego a écrit cet emoji.",
  "Même les champions doutent de toi.",
  "Tu fais semblant d’être validé.",
],

"💔": [
  "Ton cœur a quitté la conversation.",
  "Même l’amour t’a bloqué.",
  "Le mode dépression amoureuse est activé.",
  "Tu souffres encore pour quelqu’un ?",
  "Même ton emoji pleure.",
  "Ton cœur est plus fragile qu’un écran cassé.",
  "Cupidon t’a laissé en vu.",
  "Même Netflix ferait pas autant de drame.",
  "Tu tombes amoureux puis tu tombes tout court.",
  "Le romantisme t’a détruit.",
],

"💥": [
  "Ton cerveau vient d’exploser.",
  "Même les bombes font moins de dégâts.",
  "Le chaos suit chacun de tes messages.",
  "Tu débarques comme une catastrophe naturelle.",
  "Même ton emoji est violent gratuitement.",
  "Explosion mentale détectée.",
  "Tu fais trop de bruit pour rien.",
  "Le mode destruction est activé.",
  "Même les crashs sont plus organisés.",
  "Ton énergie casse tout sauf tes problèmes.",
],

"⭐": [
  "Tu te prends pour une star ?",
  "Même les étoiles brillent plus que toi.",
  "Le personnage principal imaginaire.",
  "Ton ego est dans l’espace.",
  "Même Hollywood te refuserait.",
  "Tu veux attirer l’attention encore.",
  "L’étoile du ridicule.",
  "Même le ciel t’ignore.",
  "Tu brilles seulement dans les bugs.",
  "Le VIP du néant.",
],

"🌚": [
  "Le visage de la lune fait peur.",
  "Même la nuit te trouve bizarre.",
  "Ton regard est trop suspect.",
  "Le mode inquiétant est activé.",
  "Même les ténèbres ont peur.",
  "Tu caches clairement quelque chose.",
  "L’énergie bizarre du groupe.",
  "Même la lune veut des explications.",
  "Ton emoji regarde comme un criminel.",
  "Le regard du chaos silencieux.",
],

"🌝": [
  "Pourquoi la lune sourit comme ça ?",
  "Même ton emoji est mal à l’aise.",
  "Le sourire du PNJ suspect.",
  "Tu fixes les gens bizarrement.",
  "Même la pleine lune est plus normale.",
  "Ton regard veut provoquer un malaise.",
  "La lune a perdu la raison.",
  "Même l’espace est gêné.",
  "Tu fais trop peur pour un emoji heureux.",
  "Le sourire interdit du groupe.",
],

"⚰️": [
  "Ton avenir est dans cette boîte.",
  "Même le cercueil est plus vivant.",
  "Le repos éternel de ton QI.",
  "Tu viens d’enterrer ta dignité.",
  "Même les fantômes te regardent mal.",
  "Le mode RIP est activé.",
  "Ton cerveau repose en paix.",
  "Même les morts sont plus actifs.",
  "La défaite finale.",
  "Tu viens de tuer l’ambiance.",
],

"🎭": [
  "Tu changes de personnalité toutes les 5 minutes.",
  "Même les acteurs jouent mieux.",
  "Le théâtre du mensonge continue.",
  "Ton masque tombe souvent.",
  "Même Hollywood refuse ce scénario.",
  "Tu fais trop semblant.",
  "Le drama king officiel.",
  "Même ton emoji ment.",
  "Tu joues un rôle inutile.",
  "L’Oscar du faux comportement.",
],

"🎪": [
  "Le cirque réclame son clown principal.",
  "Même les animaux du cirque sont plus normaux.",
  "Tu transformes tout en spectacle.",
  "Le chaos ambulant est arrivé.",
  "Même les clowns ont peur de toi.",
  "Tu fais rire malgré toi.",
  "Le chapiteau du désastre.",
  "Même le public veut partir.",
  "Ton existence est un show gênant.",
  "Bienvenue au festival du ridicule.",
],

"🧸": [
  "Tu fais le mignon mais ça marche pas.",
  "Même les peluches ont plus de caractère.",
  "Le mode bébé est activé.",
  "Tu cherches un câlin ou de l’attention ?",
  "Même ton emoji est trop innocent.",
  "T’as une énergie de nounours perdu.",
  "Le doudou du groupe.",
  "Même les enfants te trouvent bizarre.",
  "Tu veux être adorable mais t’es gênant.",
  "Le plushie humain.",
],

"🪞": [
  "Le miroir a crack en te voyant.",
  "Même ton reflet te juge.",
  "Tu regardes quoi exactement ?",
  "Le miroir refuse cette vision.",
  "Même les reflets ont honte.",
  "Tu cherches ton cerveau dedans ?",
  "Ton reflet veut démissionner.",
  "Même les glaces sont plus utiles.",
  "Le face-à-face avec l’échec.",
  "Ton miroir a besoin d’aide.",
],

"🧃": [
  "Même le jus a plus de saveur que toi.",
  "Tu bois ça comme un enfant de primaire.",
  "Le mode goûter est activé.",
  "Même ta boisson te juge.",
  "Ton énergie vient du sucre.",
  "Le jus essaie de te sauver.",
  "Même la paille abandonne.",
  "Tu vis grâce aux boissons sucrées.",
  "Le petit snack du chaos.",
  "Même Capri-Sun est plus mature.",
],

"🍿": [
  "Tu regardes les dramas sans aider.",
  "Même le popcorn est plus utile.",
  "Le spectateur professionnel.",
  "Tu viens juste pour observer le chaos.",
  "Même Netflix te trouve passif.",
  "Le mode voyeur est activé.",
  "Tu regardes les disputes comme une série.",
  "Même ton popcorn est gêné.",
  "T’es là uniquement pour le spectacle.",
  "Le public du désastre.",
],

"🧨": [
  "Tu exploses pour rien.",
  "Même les pétards font moins de bruit.",
  "Le danger inutile du groupe.",
  "Tu ramènes le chaos partout.",
  "Même ton emoji est instable.",
  "Le mode bombe émotionnelle.",
  "Tu détruis l’ambiance rapidement.",
  "Même les explosions ont une logique.",
  "Ton calme dure 2 secondes.",
  "Le pétard humain.",
],

"🪦": [
  "Ici repose ton intelligence.",
  "Même la tombe est plus active.",
  "Ton dernier neurone est enterré.",
  "Le RIP officiel du groupe.",
  "Même les morts te dépassent.",
  "Ton avenir est gravé ici.",
  "La fin de ton argument.",
  "Même les fantômes t’évitent.",
  "Le cimetière du QI.",
  "Ton cerveau a quitté la planète.",
],

"🍔": [
  "Tu penses plus à manger qu’à réfléchir.",
  "Même ton burger a plus de valeur.",
  "Le ventre dirige toute ta vie.",
  "Tu vois un burger et tu perds le contrôle.",
  "Même McDo te juge.",
  "Ton cerveau fonctionne à la sauce barbecue.",
  "Le chef des gourmands inutiles.",
  "Tu manges comme si y’avait plus demain.",
  "Même les frites ont peur de toi.",
  "Le fast-food est devenu ta personnalité.",
],

"🍕": [
  "Tu commandes encore au lieu de cuisiner ?",
  "Même la pizza est plus équilibrée que toi.",
  "Le fromage contrôle ton existence.",
  "Tu regardes la pizza avec plus d’amour que les humains.",
  "Même les italiens sont déçus.",
  "Ton régime est un chaos total.",
  "La pizza te connaît par prénom.",
  "Même Uber Eats te respecte plus.",
  "Tu vis en mode pepperoni.",
  "Le roi des calories.",
],

"🍜": [
  "Tu manges des nouilles comme un personnage d’anime.",
  "Même les ramens ont honte.",
  "Le bouillon nourrit ton dernier neurone.",
  "Tu slurpes trop fort.",
  "Même Naruto mange avec plus de dignité.",
  "Ton alimentation est un DLC.",
  "Le mode otaku affamé est activé.",
  "Même les baguettes veulent partir.",
  "Tu respires les épices instantanées.",
  "Le ramen est devenu ta religion.",
],

"☕": [
  "Tu bois du café pour rester inutile plus longtemps.",
  "Même la caféine abandonne.",
  "Ton sommeil est officiellement détruit.",
  "Le café essaie de réveiller un cerveau éteint.",
  "Même Starbucks te connaît trop bien.",
  "Tu trembles déjà ?",
  "Le mode insomniaque est activé.",
  "Même ton café est fatigué.",
  "Tu bois ça comme de l’eau.",
  "Le café lutte pour sauver ta journée.",
],

"🍺": [
  "Même la boisson regrette.",
  "Tu fais le grand avec un verre à la main.",
  "Le mode fête ratée est activé.",
  "Même ton équilibre te déteste.",
  "Tu racontes encore n’importe quoi après 2 gorgées.",
  "Le chaos liquide du groupe.",
  "Même ton foie demande de l’aide.",
  "Tu bois pour oublier ton niveau.",
  "Le verre cache pas la honte.",
  "Même les bouteilles te jugent.",
],

"🎮": [
  "Tu gagnes dans les jeux mais pas dans la vie.",
  "Même les PNJ sont meilleurs.",
  "Le gamer du quartier est connecté.",
  "Tu cries sur des pixels H24.",
  "Même ta console est fatiguée.",
  "Ton seul skill est virtuel.",
  "Le mode no-life est activé.",
  "Tu respawn plus que tu réussis.",
  "Même les bots te battent.",
  "Ton avenir est en mode chargement.",
],

"📱": [
  "Tu tiens ce téléphone plus que ta vie.",
  "Même ton écran est fatigué de toi.",
  "Le mode accro est activé.",
  "Tu refresh ta vie sans succès.",
  "Même ton téléphone chauffe de honte.",
  "Tu vis dans les notifications.",
  "Le smartphone contrôle ton âme.",
  "Même la batterie abandonne.",
  "Tu regardes ton écran comme un trésor.",
  "Ton temps d’écran fait peur.",
],

"💸": [
  "Ton argent disparaît plus vite que ton intelligence.",
  "Même ton portefeuille pleure.",
  "Tu dépenses sans réfléchir.",
  "Le mode ruine financière est activé.",
  "Même les pièces veulent fuir.",
  "Ton compte bancaire est traumatisé.",
  "Tu fais le riche avec 3 billets.",
  "Même les banques te surveillent.",
  "L’argent t’évite naturellement.",
  "Ton budget est en PLS.",
],

"🧢": [
  "Arrête de mentir, on t’a reconnu.",
  "Même ta casquette cache pas le mensonge.",
  "Le roi des fake stories.",
  "Tu racontes des trucs impossibles.",
  "Même ton emoji te dénonce.",
  "Le détecteur de mensonge explose.",
  "Tu bluffes plus que tu respires.",
  "Même Hollywood écrit mieux.",
  "Ton imagination est dangereuse.",
  "Le menteur officiel du groupe.",
],

"🚬": [
  "Même la fumée veut s’échapper.",
  "Tu souffles des nuages de problèmes.",
  "Le mode mystérieux raté est activé.",
  "Même ton style tousse.",
  "Tu fais le dur mais tu tousses après.",
  "La fumée cache pas le vide.",
  "Même l’air devient toxique.",
  "Tu regardes dans le vide comme un personnage triste.",
  "Le nuage du chaos est arrivé.",
  "Même ton emoji a mauvaise haleine.",
],

"🚀": [
  "Tu pars vite mais jamais loin.",
  "Même la fusée a plus de direction.",
  "Le décollage du ridicule.",
  "Tu veux atteindre les étoiles sans effort.",
  "Même la NASA refuse ce projet.",
  "Ton cerveau est en orbite.",
  "Le mode vitesse sans contrôle.",
  "Même l’espace te trouve bizarre.",
  "Tu t’envoles dans tes délires.",
  "La fusée du chaos.",
],

"🏆": [
  "Tu célèbres une victoire imaginaire.",
  "Même le trophée est surpris.",
  "Le champion du vide.",
  "Tu gagnes uniquement dans ta tête.",
  "Même les perdants te regardent mal.",
  "Le MVP du ridicule.",
  "Ton ego a gagné un prix.",
  "Même la coupe veut partir.",
  "Tu fais le boss après une chance.",
  "Le trophée de la confusion.",
],

"🎤": [
  "Tu parles trop pour rien dire.",
  "Même le micro coupe ton son.",
  "Le chanteur du désastre.",
  "Tu cries plus que tu chantes.",
  "Même Auto-Tune abandonne.",
  "Ton concert ferait fuir les gens.",
  "Le mode karaoké gênant.",
  "Même les oreilles souffrent.",
  "Tu transformes chaque phrase en spectacle.",
  "Le micro mérite mieux.",
],

"📸": [
  "Tu prends des photos mais jamais tes responsabilités.",
  "Même la caméra refuse ton angle.",
  "Le photographe du chaos.",
  "Tu cherches la validation H24.",
  "Même Instagram veut te bloquer.",
  "Ton flash révèle trop de problèmes.",
  "Le selfie du désastre.",
  "Même les filtres abandonnent.",
  "Tu prends 200 photos pour 0 résultat.",
  "Le mode influenceur raté.",
],

"🛌": [
  "Ton lit te connaît mieux que tes amis.",
  "Même ton matelas est fatigué.",
  "Le mode paresse ultime.",
  "Tu dors pour éviter les problèmes.",
  "Même ton oreiller te juge.",
  "Le champion des siestes inutiles.",
  "Tu fais carrière dans le sommeil.",
  "Même le réveil a abandonné.",
  "Ton énergie est enterrée sous la couverture.",
  "Le roi du lit.",
],

"🧼": [
  "Même le savon peut pas nettoyer tes erreurs.",
  "Le mode propre est enfin activé.",
  "Tu découvres l’hygiène aujourd’hui ?",
  "Même la mousse est choquée.",
  "Le savon travaille plus que toi.",
  "Tu veux laver quoi ? Ton passé ?",
  "Même l’eau hésite.",
  "Le nettoyage du chaos commence.",
  "Ton emoji sent la panique.",
  "Même les microbes applaudissent.",
],

"🐶": [
  "Même le chien est plus discipliné que toi.",
  "Tu cherches l’attention comme un chiot.",
  "Le canin du chaos est arrivé.",
  "Même les chiens comprennent plus vite.",
  "Tu cours après tout ce qui bouge.",
  "Le mode animal fidèle mais perdu.",
  "Même ton aboiement fait pitié.",
  "Tu remues la queue pour un compliment.",
  "Le chien du quartier est connecté.",
  "Même les croquettes te jugent.",
],

"🐱": [
  "Tu fais le mystérieux comme un chat fatigué.",
  "Même les chats ont plus de respect.",
  "Le félin du désordre est là.",
  "Tu ignores les gens puis tu reviens.",
  "Même Garfield est plus motivé.",
  "Ton énergie est en mode sieste.",
  "Tu veux de l’attention sans effort.",
  "Même les chats sont moins arrogants.",
  "Le miaou de la confusion.",
  "Tu tombes toujours sur tes problèmes.",
],

"🦁": [
  "Tu rugis mais personne a peur.",
  "Le lion du zoo imaginaire.",
  "Même Simba avait plus de charisme.",
  "Tu fais le roi sans royaume.",
  "Le prédateur du vide.",
  "Même les lions te regardent bizarrement.",
  "Ton courage disparaît vite.",
  "Tu fais le fort derrière l’écran.",
  "Le roi de rien du tout.",
  "Même la jungle t’expulse.",
],

"🐺": [
  "Le loup solitaire du groupe.",
  "Tu fais le dangereux mais t’es perdu.",
  "Même les loups vivent en équipe.",
  "Ton regard veut faire peur sans succès.",
  "Le mode alpha imaginaire.",
  "Même la pleine lune te juge.",
  "Tu hurles plus que tu réfléchis.",
  "Le prédateur low-cost.",
  "Même les chiens sont plus fiables.",
  "Ton aura est en DLC.",
],

"🐼": [
  "Même le panda est plus actif.",
  "Tu manges et dors toute la journée.",
  "Le mode paresse est validé.",
  "Même ton emoji baille.",
  "Tu vis à deux à l’heure.",
  "Le panda du quartier est réveillé.",
  "Même les bambous fuient.",
  "Ton énergie est en économie.",
  "Tu veux juste dormir tranquille.",
  "Le roi du chill inutile.",
],

"🦊": [
  "Tu fais le malin comme un renard de dessin animé.",
  "Même les renards sont moins rusés.",
  "Le mode manipulateur est activé.",
  "Ton plan est déjà raté.",
  "Même ton emoji prépare une arnaque.",
  "Tu réfléchis trop pour mal finir.",
  "Le cerveau du mal low budget.",
  "Même les pièges t’évitent.",
  "Ton sourire est suspect.",
  "Le renard du chaos.",
],

"🐸": [
  "Tu coasses plus que tu réfléchis.",
  "Même les grenouilles ont plus de style.",
  "Le marécage réclame son roi.",
  "Tu sautes partout sans avancer.",
  "Même Pepe te juge.",
  "Ton énergie amphibienne fatigue.",
  "Le mode grenouille toxique.",
  "Même les moustiques t’évitent.",
  "Tu vis dans les memes.",
  "Le crapaud du groupe.",
],

"🐔": [
  "Tu cries comme un coq à 5h du matin.",
  "Même les poules sont plus discrètes.",
  "Le fermier veut récupérer son animal.",
  "Tu paniques pour rien.",
  "Même ton emoji fait trop de bruit.",
  "Le coq du village numérique.",
  "Tu te réveilles juste pour déranger.",
  "Même les œufs ont honte.",
  "Le mode basse-cour est activé.",
  "Tu cours dès qu’il y a un problème.",
],

"🐴": [
  "Tu cours vite mais sans direction.",
  "Même les chevaux ont plus de logique.",
  "Le cheval sauvage du serveur.",
  "Tu galopes vers les problèmes.",
  "Même ton emoji transpire.",
  "Le mode cowboy raté.",
  "Tu fais trop d’efforts pour rien.",
  "Même les écuries refusent.",
  "Ton énergie part dans tous les sens.",
  "Le cheval du chaos.",
],

"🐢": [
  "Tu réfléchis à la vitesse d’une tortue.",
  "Même les escargots avancent plus vite.",
  "Le mode lent extrême.",
  "Tu charges encore la réponse ?",
  "Même Internet Explorer te dépasse.",
  "Ton cerveau démarre en retard.",
  "La patience est obligatoire avec toi.",
  "Même les tortues te jugent.",
  "Tu prends 2h pour comprendre.",
  "Le roi de la lenteur.",
],

"🐍": [
  "Le serpent officiel du groupe.",
  "Même les reptiles ont peur de toi.",
  "Tu glisses partout sauf vers le succès.",
  "Le venin parle à ta place.",
  "Même les serpents sont plus honnêtes.",
  "Ton énergie est toxique gratuitement.",
  "Tu trahis plus vite que ton ombre.",
  "Le mode vipère est activé.",
  "Même les jungles te bannissent.",
  "Le reptile du chaos.",
],

"🦈": [
  "Tu fais le requin mais t’es un poisson rouge.",
  "Même les océans te trouvent agressif.",
  "Le prédateur imaginaire du serveur.",
  "Tu veux mordre tout le monde.",
  "Même Nemo a plus de courage.",
  "Le mode danger inutile.",
  "Tu tournes autour des problèmes.",
  "Même les vagues te rejettent.",
  "Le requin du ridicule.",
  "Ton aura sent l’eau salée et les erreurs.",
],

"🐧": [
  "Même les pingouins marchent mieux que toi.",
  "Tu glisses dans les problèmes naturellement.",
  "Le mode froid maladroit.",
  "Même la banquise te juge.",
  "Tu bouges comme un personnage buggué.",
  "Le pingouin du désordre.",
  "Même ton emoji tombe souvent.",
  "Tu fais rire sans parler.",
  "Le roi des déplacements bizarres.",
  "Même les poissons te dépassent.",
],

"🦥": [
  "Tu bouges à la vitesse d’un paresseux fatigué.",
  "Même ton emoji dort debout.",
  "Le mode ultra lent est activé.",
  "Tu mets 3 jours à répondre.",
  "Même les arbres te dépassent.",
  "Ton énergie est en maintenance.",
  "Le paresseux du serveur.",
  "Tu fais tout au ralenti.",
  "Même les tortues s’impatientent.",
  "Le champion de la flemme.",
],

"🐝": [
  "Tu piques les gens gratuitement.",
  "Même les abeilles travaillent plus.",
  "Le mode bourdonnement inutile.",
  "Tu tournes autour sans rien faire.",
  "Même le miel est plus doux.",
  "Le moustique premium du groupe.",
  "Tu déranges tout le monde.",
  "Même les ruches te bannissent.",
  "Ton énergie est irritante.",
  "L’insecte du chaos.",
],

"🐙": [
  "T’as 8 problèmes mais toujours zéro solution.",
  "Même le poulpe est moins confus que toi.",
  "Tu t’emmêles dans tout comme des tentacules.",
  "Le mode chaos multi-bras est activé.",
  "Même l’océan ne veut pas de toi.",
  "T’agis dans tous les sens sans logique.",
  "Ton cerveau a plusieurs directions… aucune bonne.",
  "Même les algues te jugent.",
  "Tu touches à tout mais tu comprends rien.",
  "Le monstre marin du désordre.",
],

"🦖": [
  "Même les dinosaures sont plus modernes que toi.",
  "Tu es resté bloqué à l’ère préhistorique.",
  "Le T-Rex du cerveau absent.",
  "Tu rugis mais ça fait aucun effet.",
  "Même les fossiles ont plus d’avenir.",
  "Ton évolution a crashé.",
  "Tu fais peur… mais surtout rire.",
  "Le mode Jurassic erreur est activé.",
  "Même les météores t’évitent.",
  "Le dinosaure du chaos.",
],

"🐞": [
  "Même les insectes ont plus d’impact que toi.",
  "Tu bugs comme un logiciel cassé.",
  "Le mode parasite du système.",
  "Même les feuilles te refusent.",
  "Tu es petit mais toujours gênant.",
  "Le bug vivant du chat.",
  "Ton existence est une erreur système.",
  "Même les coccinelles te fuient.",
  "Tu apparais comme un glitch.",
  "Le micro chaos du groupe.",
],

"🪲": [
  "Même les scarabées avancent mieux que toi.",
  "Tu ramasses les problèmes comme des déchets.",
  "Le mode insecte inutile est activé.",
  "Même la terre te rejette.",
  "Tu tournes en rond sans but.",
  "Le bug rampant du système.",
  "Ton énergie est recyclée zéro fois.",
  "Même les fourmis t’évitent.",
  "Tu fais du bruit pour rien.",
  "Le scarabée du chaos.",
],

"🐛": [
  "Tu rampes dans les problèmes lentement.",
  "Même une chenille avance mieux.",
  "Le mode transformation ratée.",
  "Tu devais devenir quelque chose… raté.",
  "Même les feuilles te fuient.",
  "Le ver du désespoir.",
  "Tu consommes sans évoluer.",
  "Même les plantes t’ignorent.",
  "Ton avenir est en mode bug.",
  "Le parasite du chat.",
],

"🦗": [
  "Même les criquets font plus de bruit utile.",
  "Tu sautes sans jamais avancer.",
  "Le mode bruit inutile est activé.",
  "Même les champs te supportent pas.",
  "Tu apparaîs puis tu disparais sans impact.",
  "Le criquet du vide.",
  "Ton énergie est intermittente.",
  "Même les herbes te jugent.",
  "Tu fais du son pour rien.",
  "Le bug sonore du groupe.",
],

"🦟": [
  "Tu piques tout le monde sans raison.",
  "Même les moustiques ont plus de respect.",
  "Le mode parasite activé.",
  "Tu déranges sans apporter rien.",
  "Même les murs te détestent.",
  "Le moustique du chaos.",
  "Ton existence est irritante.",
  "Même les insecticides t’évitent.",
  "Tu buzz pour rien.",
  "Le bug volant du serveur.",
],

"🪰": [
  "Même les mouches sont plus rapides que toi.",
  "Tu traînes toujours autour des problèmes.",
  "Le mode gêne permanente est activé.",
  "Tu t’installes partout inutilement.",
  "Même les déchets t’acceptent pas.",
  "La mouche du désordre.",
  "Tu reviens toujours au même endroit.",
  "Même les odeurs te supportent pas.",
  "Tu es collant sans raison.",
  "Le parasite du groupe.",
],

"🕷️": [
  "Tu tisses des problèmes partout.",
  "Même les araignées ont plus de plan.",
  "Le mode piège inutile est activé.",
  "Tu attends que ça tombe sans agir.",
  "Même les coins sombres te fuient.",
  "La toile du chaos.",
  "Tu emprisonnes rien sauf toi-même.",
  "Même les mouches t’évitent.",
  "Ton plan est fragile comme une toile.",
  "L’araignée du désastre.",
],

"🐚": [
  "Tu restes fermé comme une coquille vide.",
  "Même les plages t’oublient.",
  "Le mode silence inutile est activé.",
  "Tu réponds jamais au bon moment.",
  "Même la mer te rejette.",
  "La coquille du vide.",
  "Ton intérieur est vide mais bruyant.",
  "Tu fais semblant d’être profond.",
  "Même les vagues t’ignorent.",
  "Le coquillage du néant.",
],

"🌪️": [
  "Tu arrives et tu détruis tout.",
  "Même les tempêtes ont plus de contrôle.",
  "Le chaos naturel du groupe.",
  "Tu fais du bruit sans direction.",
  "Même la météo a peur de toi.",
  "La tornade du désordre.",
  "Tu tournes sans jamais avancer.",
  "Même les nuages te jugent.",
  "Ton énergie est incontrôlable.",
  "Le cyclone humain.",
],

"🌋": [
  "Tu exploses pour rien.",
  "Même les volcans préviennent avant.",
  "Le mode destruction gratuite est activé.",
  "Tu accumules puis tu exploses inutilement.",
  "Même la lave a plus de logique.",
  "Le volcan du chaos.",
  "Tu brûles tout autour de toi.",
  "Même les montagnes t’évitent.",
  "Ton calme est une illusion.",
  "L’éruption du groupe.",
],

"❄️": [
  "Même ton cœur est congelé.",
  "Tu fais le froid sans raison.",
  "Le mode émotion gelée est activé.",
  "Même l’hiver est plus chaleureux.",
  "Tu bloques toute ambiance.",
  "La glace du serveur.",
  "Ton énergie est inexistante.",
  "Même les pingouins ont pitié.",
  "Tu refroidis tout le monde.",
  "Le freezer humain.",
],

"🌈": [
  "Même l’arc-en-ciel doute de ton optimisme.",
  "Tu vois la vie en couleurs mais tout est flou.",
  "Le mode rêve activé sans résultats.",
  "Même les nuages te jugent.",
  "Tu crois que tout est magique ici.",
  "L’illusion colorée du groupe.",
  "Même la pluie te rattrape vite.",
  "Ton bonheur est en version démo.",
  "Tu brilles mais sans impact.",
  "Le monde imaginaire du serveur.",
],

"⚡": [
  "Tu veux aller vite mais tu crash souvent.",
  "Même l’électricité te fuit.",
  "Le mode énergie instable est activé.",
  "Tu fais du bruit sans résultat.",
  "Même les prises te refusent.",
  "Ton cerveau court-circuite souvent.",
  "La foudre du chaos.",
  "Tu charges mais tu n’exécutes rien.",
  "Même les orages sont plus organisés.",
  "Le bug électrique humain.",
],

"💡": [
  "Une idée ? Ça doit être rare chez toi.",
  "Même l’ampoule hésite à s’allumer.",
  "Le mode pseudo-intelligence est activé.",
  "Tu crois avoir compris mais non.",
  "Même la lumière te juge.",
  "L’idée brillante… mais imaginaire.",
  "Ton cerveau clignote parfois.",
  "Même les lampes te fuient.",
  "Tu fais semblant d’avoir une idée.",
  "Le faux génie du groupe.",
],

"🔒": [
  "Même ton cerveau est verrouillé.",
  "Tu bloques tout même les solutions.",
  "Le mode fermé à la réflexion est activé.",
  "Même les clés te fuient.",
  "Tu refuses de comprendre parfois.",
  "Le coffre vide du groupe.",
  "Ton mental est en mode sécurisé inutile.",
  "Même les portes t’évitent.",
  "Tu restes bloqué dans tes idées.",
  "Le cadenas du désastre.",
],

"🔓": [
  "Tu ouvres tout sauf ton esprit.",
  "Même les portes regrettent.",
  "Le mode liberté sans contrôle est activé.",
  "Tu libères le chaos sans le savoir.",
  "Même les serrures paniquent.",
  "Le cadenas cassé du groupe.",
  "Tu crois être libre mais perdu.",
  "Même les systèmes te craignent.",
  "Tu déverrouilles des problèmes.",
  "Le bug ouvert du serveur.",
],

"📦": [
  "Même les colis ne veulent pas de toi.",
  "Tu arrives mais personne t’attend.",
  "Le mode livraison ratée est activé.",
  "Tu es plein de surprises inutiles.",
  "Même les cartons te jugent.",
  "Le paquet du chaos.",
  "Ton contenu est toujours décevant.",
  "Même les transporteurs te fuient.",
  "Tu restes fermé sans raison.",
  "Le colis du désastre.",
],

"📌": [
  "Tu restes accroché aux problèmes.",
  "Même les punaises te rejettent.",
  "Le mode fixation inutile est activé.",
  "Tu bloques tout sans avancer.",
  "Même les murs veulent te fuir.",
  "Le point fixe du chaos.",
  "Tu t’accroches à rien d’utile.",
  "Même les tableaux te refusent.",
  "Tu restes coincé dans tes idées.",
  "Le bug accroché du groupe.",
],

"🫀": [
  "Ton cœur fonctionne en mode fragile.",
  "Même les émotions plantent.",
  "Le mode sentimental instable est activé.",
  "Tu ressens tout mais mal.",
  "Même les sentiments te fuient.",
  "Le cœur du chaos émotionnel.",
  "Tu vibres pour rien.",
  "Même l’amour te déconnecte.",
  "Ton émotion est instable.",
  "Le bug affectif du groupe.",
],

"🫁": [
  "Même ta respiration est stressée.",
  "Tu paniques pour respirer normalement.",
  "Le mode survie inutile est activé.",
  "Même l’air te juge.",
  "Tu vis en mode alerte permanente.",
  "Les poumons du chaos.",
  "Tu stresses même sans raison.",
  "Même l’oxygène te fatigue.",
  "Ton souffle est instable.",
  "Le système respiratoire en PLS.",
],

"🧻": [
  "Même le papier t’abandonne.",
  "Tu t’essuies les problèmes mais ça revient.",
  "Le mode nettoyage inutile est activé.",
  "Tu règles rien du tout.",
  "Même les rouleaux te fuient.",
  "Le papier du chaos.",
  "Tu t’effaces sans impact.",
  "Même les toilettes te jugent.",
  "Ton utilité est limitée.",
  "Le wipe du groupe.",
],

"🪫": [
  "Même ta batterie refuse de charger.",
  "Tu es toujours en mode faible énergie.",
  "Le mode extinction est proche.",
  "Tu n’as plus de motivation.",
  "Même les chargeurs t’abandonnent.",
  "La batterie du désastre.",
  "Tu fonctionnes à 1%.",
  "Même ton énergie disparaît.",
  "Tu bugs à chaque action.",
  "Le système en panne.",
],

"🔋": [
  "Tu crois être chargé mais tu vides vite.",
  "Même l’énergie te fuit rapidement.",
  "Le mode illusion de puissance est activé.",
  "Tu démarres fort puis crash.",
  "Même les piles doutent.",
  "La batterie instable du groupe.",
  "Tu fais semblant d’être motivé.",
  "Même les systèmes te surchauffent.",
  "Ton énergie est temporaire.",
  "Le faux power-up.",
],

"🧿": [
  "Même le mauvais œil a peur de toi.",
  "Tu crois être protégé mais c’est toi le problème.",
  "Le mode mystique inutile est activé.",
  "Tu regardes les autres comme un bug spirituel.",
  "Même les énergies t’évitent.",
  "Ton aura est en version test.",
  "Le charme occulte du chaos.",
  "Tu portes un symbole mais pas de chance.",
  "Même le destin te mute.",
  "Le talisman du désordre.",
],

"🔮": [
  "Tu prédis rien sauf des erreurs.",
  "Même la boule de cristal refuse de fonctionner.",
  "Le voyant du faux futur.",
  "Tu inventes ton avenir au hasard.",
  "Même la magie te bloque.",
  "Ton destin est en chargement infini.",
  "Le mage du chaos mental.",
  "Tu regardes le futur mais tu comprends rien.",
  "Même les prédictions te fuient.",
  "Le devin du vide.",
],

"🎲": [
  "Ta vie est un mauvais lancer de dé.",
  "Même la chance t’a unfollow.",
  "Le mode hasard catastrophique est activé.",
  "Tu joues mais tu perds toujours.",
  "Même les jeux te bannissent.",
  "Le dé du désastre.",
  "Tu relies tout au hasard sans réfléchir.",
  "Même les probabilités te détestent.",
  "Ton destin est mal scripté.",
  "Le RNG humain raté.",
],

"🧩": [
  "Même les pièces refusent de t’assembler.",
  "Tu ne rentres dans aucun système.",
  "Le puzzle du chaos incomplet.",
  "Tu es toujours une pièce manquante.",
  "Même les boîtes te rejettent.",
  "Ton cerveau est mal assemblé.",
  "Le casse-tête impossible du groupe.",
  "Tu essaies mais rien ne colle.",
  "Même la logique abandonne.",
  "Le bug de l’assemblage.",
],

"🧷": [
  "Même les épingles te lâchent.",
  "Tu tiens rien correctement.",
  "Le mode attache fragile est activé.",
  "Tu essaies de fixer mais ça tombe.",
  "Même les tissus te rejettent.",
  "Le maintien du chaos.",
  "Tout ce que tu touches se défait.",
  "Même la stabilité te fuit.",
  "Tu ne tiens jamais en place.",
  "Le fixeur raté.",
],

"🪤": [
  "Tu tombes dans tous les pièges.",
  "Même les souris sont plus malignes.",
  "Le mode victime activé.",
  "Tu avances sans regarder.",
  "Même les pièges t’appellent.",
  "Le piège du chaos.",
  "Tu te fais avoir facilement.",
  "Même les systèmes simples te bloquent.",
  "Tu fonces sans réfléchir.",
  "Le rat du désastre.",
],

"🪜": [
  "Même les échelles te dépassent.",
  "Tu n’arrives jamais à monter.",
  "Le mode progression cassée est activé.",
  "Tu essaies de grimper mais tu glisses.",
  "Même les murs sont contre toi.",
  "L’échelle du chaos.",
  "Ton ascension est bloquée.",
  "Même les marches te rejettent.",
  "Tu avances mais sans progrès.",
  "Le climb impossible.",
],

"🧱": [
  "Même les briques sont plus utiles que toi.",
  "Tu bloques tout sur ton passage.",
  "Le mur du désordre est activé.",
  "Tu ne laisses rien passer.",
  "Même les constructions te jugent.",
  "La brique du chaos.",
  "Tu es solide mais inutile.",
  "Même les chantiers t’évitent.",
  "Tu restes figé sans avancer.",
  "Le blocage humain.",
],

"🪙": [
  "Même la monnaie te fuit.",
  "Tu n’as jamais de chance financière.",
  "Le mode richesse imaginaire est activé.",
  "Tu comptes des pièces inexistantes.",
  "Même les banques te refusent.",
  "La pièce du chaos.",
  "Ton argent disparaît mystérieusement.",
  "Même les portefeuilles te quittent.",
  "Tu vis en mode pauvre logique.",
  "Le coin du désastre.",
],

"🧲": [
  "Tu attires les problèmes uniquement.",
  "Même les aimants te fuient.",
  "Le mode attraction négative est activé.",
  "Tu colles aux ennuis.",
  "Même les métaux t’évitent.",
  "L’aimant du chaos.",
  "Tu ne fais qu’attirer le pire.",
  "Même les forces naturelles te rejettent.",
  "Ton énergie est toxique magnétique.",
  "Le champ du désastre.",
],

"🪫": [
  "Même ta batterie refuse de te sauver.",
  "Tu es toujours à court d’énergie.",
  "Le mode extinction rapide est activé.",
  "Tu tiens jamais longtemps.",
  "Même les chargeurs te fuient.",
  "La batterie du chaos.",
  "Tu crashes avant d’agir.",
  "Même les systèmes t’abandonnent.",
  "Ton énergie est inexistante.",
  "Le low power humain.",
],

"📡": [
  "Même le signal te trouve nul.",
  "Tu captes rien de la réalité.",
  "Le mode connexion instable est activé.",
  "Tu reçois mais tu comprends pas.",
  "Même les antennes te bloquent.",
  "Le signal du chaos.",
  "Tu es toujours hors réseau.",
  "Même les satellites t’ignorent.",
  "Ton info est toujours perdue.",
  "Le bug de transmission.",
],

    if (responses[emoji]) {
      const randomResponse =
        responses[emoji][Math.floor(Math.random() * responses[emoji].length)];

      return message.reply(randomResponse);
    }
  },
};
